# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-06 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.BooleanField(default=False)),
                ('has_kids', models.BooleanField(default=False)),
                ('student_loan', models.IntegerField(default=0)),
                ('pets', models.BooleanField(default=False)),
                ('an_artist', models.BooleanField(default=False)),
                ('proposing', models.BooleanField(default=False)),
                ('athletic', models.BooleanField(default=False)),
                ('divorced', models.BooleanField(default=False)),
                ('outgoing', models.BooleanField(default=False)),
                ('figurine_stuffs', models.BooleanField(default=False)),
                ('peaceful', models.BooleanField(default=False)),
                ('moved', models.BooleanField(default=False)),
                ('into_music', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('location', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemApp.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemApp.Vendor'),
        ),
        migrations.AddField(
            model_name='features',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemApp.Individual'),
        ),
        migrations.AlterUniqueTogether(
            name='features',
            unique_together=set([('user',)]),
        ),
    ]
